name: env_test

on: workflow_dispatch

env:
  APP_ENV: development

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: echo "App environment is $APP_ENV"
      
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print stage variable
        run: echo "Stage = $STAGE"
        env:
          STAGE: test
